version: '3.8'
services:
  mongodb:
    image: mongo
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=max
      - MONGO_INITDB_ROOT_PASSWORD=secret

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - logs:/app/logs
      - /app/node_modules 
      - ./backend:/app
    ports:
      - '80:80'
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"
    stdin_open: true  
    tty: true
    depends_on:
      - backend

volumes:
  mongodb:
  logs: