version: '3.8'
services:
  mongoDB:
    image: mongo
    restart: "no"
# volumes used for save date permenantly after shutdown or restart container
    volumes:
      - my_data:/data/db
  node-web:
#if you have only docker file
#   build: .
#if you have more than dockerfile on same dir below approach is better
    build: 
      dockerfile: Dockerfile
    depends_on:
      - mongoDB
    ports:
      - "8080:5050"
volumes:
  my_data:
